{{- if and $.Values.secrets $.Values.secrets.enable }}
---
apiVersion: v1
data:
{{ tpl (toYaml $.Values.secrets.data) $ | indent 4 }}
kind: Secret
metadata:
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
type: Opaque
{{- end }}
