{{- if and $.Values.hpa $.Values.hpa.enable }}
{{- if eq $.Values.hpa.type "Pods" }}
---
apiVersion: deckhouse.io/v1beta1
kind: PodMetric
metadata:
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
spec:
  query: {{ tpl ($.Values.hpa.podMetric.query) $ }}
{{- end }}
{{- if eq $.Values.hpa.type "Service" }}
---
apiVersion: deckhouse.io/v1beta1
kind: ServiceMetric
metadata:
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
spec:
  query: {{ tpl ($.Values.hpa.serviceMetric.query) $ }}
{{- end }}
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
{{- if $.Values.deployment.enable}}
    kind: Deployment
{{- else if $.Values.statefulset.enable}}
    kind: StatefulSet
{{- end}}
    name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
  minReplicas: {{ tpl ($.Values.hpa.minReplicas) $ }}
  maxReplicas: {{ tpl ($.Values.hpa.maxReplicas) $ }}
{{- if $.Values.hpa.behavior }}
  behavior:
{{ tpl (toYaml $.Values.hpa.behavior) $ | indent 4 }}
{{- end }}
  metrics:
{{- if eq $.Values.hpa.type "Pods" }}
  - type: Pods
    pods:
      metric:
        name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
      target:
        type: AverageValue
        averageValue: {{ tpl ($.Values.hpa.averageValue) $ }}
{{- else if eq $.Values.hpa.type "Service"}}
  - type: Object
    object:
      describedObject:
        apiVersion: v1
        kind: Service
        name: {{ tpl ($.Values.hpa.serviceMetric.serviceName) $ }}
      metric:
        name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
      target:
        type: Value
        value: {{ tpl ($.Values.hpa.averageValue) $ }}
{{- end }}
{{- if $.Values.hpa.metrics }}
{{ tpl (toYaml $.Values.hpa.metrics) $ | indent 2 }}
{{- end }}
{{- end }}
