{{- if and $.Values.ingress $.Values.ingress.enable }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if $.Values.ingress.annotations }}
  annotations:
{{ tpl (toYaml $.Values.ingress.annotations) $ | indent 8 }}
{{- end }}
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
spec:
  ingressClassName: {{ tpl $.Values.ingress.controller $ }}
  rules:
{{- range $_, $host := $.Values.ingress.hosts }}
  - host: {{ tpl $host $ }}
    http:
      paths:
{{- if and $.Values.grpcGateway $.Values.grpcGateway.enable }}
      - path: /grpc.
        pathType: Prefix
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.ingress.service.port }}
{{- range $_, $service := $.Values.grpcGateway.envoy.transcoderServices }}
      - path: /{{ $service }}
        pathType: Prefix
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.ingress.service.port }}
{{- end }}
{{- range $_, $service := $.Values.grpcGateway.envoy.extraTranscoderServices }}
      - path: /{{ $service }}
        pathType: Prefix
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.ingress.service.port }}
{{- end }}
{{- else }}
      - pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.ingress.service.port }}
{{- end }}
{{- end }}
{{- if (index $.Values.ingress "tls-secret-name") }}
  tls:
  - hosts:
{{- range $_, $host := $.Values.ingress.hosts }}
    - {{ tpl $host $ }}
{{- end }}
    secretName: {{ tpl (index $.Values.ingress "tls-secret-name") $ }}
{{- end }}
{{- range $_, $extrahost := $.Values.ingress.extraIngresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if $extrahost.annotations }}
  annotations:
{{ tpl (toYaml $extrahost.annotations) $ | indent 8 }}
{{- end }}
  name: {{ tpl $extrahost.name $ }}
spec:
  ingressClassName: {{ tpl $extrahost.controller $ }}
  rules:
{{- range $_, $host := $extrahost.hosts }}
  - host: {{ tpl $host $ }}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: {{ tpl $extrahost.service.name $ }}
            port:
              name: {{ tpl $extrahost.service.port $ }}
{{- end }}
{{- if (index $extrahost "tls-secret-name") }}
  tls:
  - hosts:
{{- range $_, $host := $extrahost.hosts }}
    - {{ tpl $host $ }}
{{- end }}
    secretName: {{ tpl (index $extrahost "tls-secret-name") $ }}
{{- end }}
{{- end }}

{{- if and $.Values.grpcGateway $.Values.grpcGateway.enable }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
{{- if $.Values.grpcGateway.ingress.annotations }}
{{ tpl (toYaml $.Values.grpcGateway.ingress.annotations) $ | indent 4 }}
{{- end }}
  name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}-gateway
spec:
  ingressClassName: {{ tpl $.Values.ingress.controller $ }}
  rules:
{{- range $_, $host := $.Values.ingress.hosts }}
  - host: {{ tpl $host $ }}
    http:
      paths:
      - path: /()
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
      - path: /(index.css)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
      - path: /(swagger-ui.css)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
      - path: /(favicon-.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
      - path: /(swagger-.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
      - path: /(.*css)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
      - path: /(api.swagger.json)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
      - path: /gateway(?:/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ default $.Chart.Name $.Values.nameOverride | trunc 63 | replace "." "-" }}
            port:
              name: {{ $.Values.grpcGateway.ingress.servicePort }}
{{- end }}
{{- if (index $.Values.ingress "tls-secret-name") }}
  tls:
  - hosts:
{{- range $_, $host := $.Values.ingress.hosts }}
    - {{ tpl $host $ }}
{{- end }}
    secretName: {{ tpl (index $.Values.ingress "tls-secret-name") $ }}
{{- end }}
{{- end }}
{{- end }}
